export const juzData = [
  {
    id: 1,
    title: 'Juz 1',
    arabic: 'آلم',
    english: 'Alif Lam Meem',
    range: '1:1 - 2:141',
  },
  {
    id: 2,
    title: 'Juz 2',
    arabic: 'سَيَقُولُ',
    english: 'Sayaqool',
    range: '2:142 - 2:252',
  },
  {
    id: 3,
    title: 'Juz 3',
    arabic: 'تِلْكَ ٱلْرُّسُلُ',
    english: 'Tilkal Rusulu',
    range: '2:253 - 3:92',
  },
  {
    id: 4,
    title: 'Juz 4',
    arabic: 'لَنْ تَنَالُوْ الْبِرَّ',
    english: 'Lan tanaloo albirra',
    range: '3:93 - 4:23',
  },
  {
    id: 5,
    title: 'Juz 5',
    arabic: 'وَٱلْمُحْصَنَاتُ',
    english: 'Wal Mohsanatu',
    range: '4:24 - 4:147',
  },
  {
    id: 6,
    title: 'Juz 6',
    arabic: 'لَا يُحِبُّ ٱللهُ',
    english: 'La Yuhibbullah',
    range: '4:148 - 5:81',
  },
  {
    id: 7,
    title: 'Juz 7',
    arabic: 'وَإِذَا سَمِعُوا',
    english: 'Wa Iza Samiu',
    range: '5:82 - 6:110',
  },
  {
    id: 8,
    title: 'Juz 8',
    arabic: 'وَلَوْ أَنَّنَا',
    english: 'Wa Lau Annana',
    range: '6:111 - 7:87',
  },
  {
    id: 9,
    title: 'Juz 9',
    arabic: 'قَالَ ٱلْمَلَأُ',
    english: 'Qalal Malao',
    range: '7:88 - 8:40',
  },
  {
    id: 10,
    title: 'Juz 10',
    arabic: 'وَٱعْلَمُواْ',
    english: "Wa A'lamu",
    range: '8:41 - 9:92',
  },
  {
    id: 11,
    title: 'Juz 11',
    arabic: 'يَعْتَذِرُونَ',
    english: 'Yatazeroon',
    range: '9:93 - 11:5',
  },
  {
    id: 12,
    title: 'Juz 12',
    arabic: 'وَمَا مِن دَآبَّةٍ',
    english: 'Wa Mamin Da’abat',
    range: '11:6 - 12:52',
  },
  {
    id: 13,
    title: 'Juz 13',
    arabic: 'وَمَا أُبَرِّئُ',
    english: 'Wa Maaa Ubarriu',
    range: '12:53 - 14:52',
  },
  {
    id: 14,
    title: 'Juz 14',
    arabic: 'رُبَمَا',
    english: 'Rubama',
    range: '15:1 - 16:128',
  },
  {
    id: 15,
    title: 'Juz 15',
    arabic: 'سُبْحَانَ ٱلَّذِى',
    english: 'Subhanalladhi',
    range: '17:1 - 18:74',
  },
  {
    id: 16,
    title: 'Juz 16',
    arabic: 'قَالَ أَلَمْ',
    english: 'Qal Alam',
    range: '18:75 - 20:135',
  },
  {
    id: 17,
    title: 'Juz 17',
    arabic: 'ٱقْتَرَبَ لِلْنَّاسِ',
    english: 'Aqtaribatin Naasi',
    range: '21:1 - 22:78',
  },
  {
    id: 18,
    title: 'Juz 18',
    arabic: 'قَدْ أَفْلَحَ',
    english: 'Qadd Aflaha',
    range: '23:1 - 25:20',
  },
  {
    id: 19,
    title: 'Juz 19',
    arabic: 'وَقَالَ ٱلَّذِينَ',
    english: 'Wa Qalallazina',
    range: '25:21 - 27:55',
  },
  {
    id: 20,
    title: 'Juz 20',
    arabic: 'أَمَّنْ خَلَقَ',
    english: 'A’man Khalaqa',
    range: '27:56 - 29:45',
  },
  {
    id: 21,
    title: 'Juz 21',
    arabic: 'اتْلُ مَا أُوْحِيَ',
    english: 'Utlu Ma Oohi',
    range: '29:46 - 33:30',
  },
  {
    id: 22,
    title: 'Juz 22',
    arabic: 'وَمَنْ يَّقْنُتْ',
    english: 'Wa Manyaqnut',
    range: '33:31 - 36:27',
  },
  {
    id: 23,
    title: 'Juz 23',
    arabic: 'وَمَآ لِيَ',
    english: 'Wa Mali',
    range: '36:28 - 39:31',
  },
  {
    id: 24,
    title: 'Juz 24',
    arabic: 'فَمَنْ أَظْلَمُ',
    english: 'Faman Azlam',
    range: '39:32 - 41:46',
  },
  {
    id: 25,
    title: 'Juz 25',
    arabic: 'إِلَيْهِ يُرَدُّ',
    english: 'Elahe Yuruddu',
    range: '41:47 - 45:37',
  },
  {
    id: 26,
    title: 'Juz 26',
    arabic: 'حم',
    english: 'Ha Meem',
    range: '46:1 - 51:30',
  },
  {
    id: 27,
    title: 'Juz 27',
    arabic: 'قَالَ فَمَا خَطْبُكُم',
    english: 'Qala Fama Khatbukum',
    range: '51:31 - 57:29',
  },
  {
    id: 28,
    title: 'Juz 28',
    arabic: 'قَدْ سَمِعَ ٱللهُ',
    english: 'Qadd Sami Allah',
    range: '58:1 - 66:12',
  },
  {
    id: 29,
    title: 'Juz 29',
    arabic: 'تَبَارَكَ ٱلَّذِى',
    english: 'Tabarakalladhi',
    range: '67:1 - 77:50',
  },
  {
    id: 30,
    title: 'Juz 30',
    arabic: 'عَمَّ',
    english: "Amma Yatasa'aloon",
    range: '78:1 - 114:6',
  },
];
