export const surahs = [
  {
    id: 1,
    name: 'الفاتحة',
    transliteration: 'Al-Fatihah',
    translation: 'کھولنے والی',
    type: 'Mecca',
    total_verses: 7,
  },
  {
    id: 2,
    name: 'البقرة',
    transliteration: 'Al-Baqarah',
    translation: 'گائے',
    type: 'Medina',
    total_verses: 286,
  },
  {
    id: 3,
    name: 'آل عمران',
    transliteration: "Ali 'Imran",
    translation: 'عمران کا خاندان',
    type: 'Medina',
    total_verses: 200,
  },
  {
    id: 4,
    name: 'النساء',
    transliteration: 'An-Nisa',
    translation: 'عورت',
    type: 'Medina',
    total_verses: 176,
  },
  {
    id: 5,
    name: 'المائدة',
    transliteration: "Al-Ma'idah",
    translation: 'دسترخوان',
    type: 'Medina',
    total_verses: 120,
  },
  {
    id: 6,
    name: 'الأنعام',
    transliteration: "Al-An'am",
    translation: 'مویشی',
    type: 'Mecca',
    total_verses: 165,
  },
  {
    id: 7,
    name: 'الأعراف',
    transliteration: "Al-A'raf",
    translation: 'اونچی جگہ',
    type: 'Mecca',
    total_verses: 206,
  },
  {
    id: 8,
    name: 'الأنفال',
    transliteration: 'Al-Anfal',
    translation: 'مال غنیمت',
    type: 'Medina',
    total_verses: 75,
  },
  {
    id: 9,
    name: 'التوبة',
    transliteration: 'At-Tawbah',
    translation: 'توبہ',
    type: 'Medina',
    total_verses: 129,
  },
  {
    id: 10,
    name: 'يونس',
    transliteration: 'Yunus',
    translation: 'یونس',
    type: 'Mecca',
    total_verses: 109,
  },
  {
    id: 11,
    name: 'هود',
    transliteration: 'Hud',
    translation: 'حود',
    type: 'Mecca',
    total_verses: 123,
  },
  {
    id: 12,
    name: 'يوسف',
    transliteration: 'Yusuf',
    translation: 'یوسف',
    type: 'Mecca',
    total_verses: 111,
  },
  {
    id: 13,
    name: 'الرعد',
    transliteration: "Ar-Ra'd",
    translation: 'گرج',
    type: 'Medina',
    total_verses: 43,
  },
  {
    id: 14,
    name: 'ابراهيم',
    transliteration: 'Ibrahim',
    translation: 'ابراہیم',
    type: 'Mecca',
    total_verses: 52,
  },
  {
    id: 15,
    name: 'الحجر',
    transliteration: 'Al-Hijr',
    translation: 'پتھر',
    type: 'Mecca',
    total_verses: 99,
  },
  {
    id: 16,
    name: 'النحل',
    transliteration: 'An-Nahl',
    translation: 'شہد کی مکھی',
    type: 'Mecca',
    total_verses: 128,
  },
  {
    id: 17,
    name: 'الإسراء',
    transliteration: 'Al-Isra',
    translation: 'رات کا صفر',
    type: 'Mecca',
    total_verses: 111,
  },
  {
    id: 18,
    name: 'الكهف',
    transliteration: 'Al-Kahf',
    translation: 'غار',
    type: 'Mecca',
    total_verses: 110,
  },
  {
    id: 19,
    name: 'مريم',
    transliteration: 'Maryam',
    translation: 'مریم',
    type: 'Mecca',
    total_verses: 98,
  },
  {
    id: 20,
    name: 'طه',
    transliteration: 'Taha',
    translation: 'طٰہٰ',
    type: 'Mecca',
    total_verses: 135,
  },
  {
    id: 21,
    name: 'الأنبياء',
    transliteration: 'Al-Anbya',
    translation: 'پیغمبر',
    type: 'Mecca',
    total_verses: 112,
  },
  {
    id: 22,
    name: 'الحج',
    transliteration: 'Al-Hajj',
    translation: 'حج',
    type: 'Medina',
    total_verses: 78,
  },
  {
    id: 23,
    name: 'المؤمنون',
    transliteration: "Al-Mu'minun",
    translation: 'مومنین',
    type: 'Mecca',
    total_verses: 118,
  },
  {
    id: 24,
    name: 'النور',
    transliteration: 'An-Nur',
    translation: 'نور',
    type: 'Medina',
    total_verses: 64,
  },
  {
    id: 25,
    name: 'الفرقان',
    transliteration: 'Al-Furqan',
    translation: 'صحیح اور غلط میں فرق کرنے والی کتاب',
    type: 'Mecca',
    total_verses: 77,
  },
  {
    id: 26,
    name: 'الشعراء',
    transliteration: "Ash-Shu'ara",
    translation: 'شعراٗ',
    type: 'Mecca',
    total_verses: 227,
  },
  {
    id: 27,
    name: 'النمل',
    transliteration: 'An-Naml',
    translation: 'چیونٹی',
    type: 'Mecca',
    total_verses: 93,
  },
  {
    id: 28,
    name: 'القصص',
    transliteration: 'Al-Qasas',
    translation: 'قصے',
    type: 'Mecca',
    total_verses: 88,
  },
  {
    id: 29,
    name: 'العنكبوت',
    transliteration: "Al-'Ankabut",
    translation: 'مکڑی',
    type: 'Mecca',
    total_verses: 69,
  },
  {
    id: 30,
    name: 'الروم',
    transliteration: 'Ar-Rum',
    translation: 'روم',
    type: 'Mecca',
    total_verses: 60,
  },
  {
    id: 31,
    name: 'لقمان',
    transliteration: 'Luqman',
    translation: 'لقمان',
    type: 'Mecca',
    total_verses: 34,
  },
  {
    id: 32,
    name: 'السجدة',
    transliteration: 'As-Sajdah',
    translation: 'سجدہ',
    type: 'Mecca',
    total_verses: 30,
  },
  {
    id: 33,
    name: 'الأحزاب',
    transliteration: 'Al-Ahzab',
    translation: 'متحد گروہ',
    type: 'Medina',
    total_verses: 73,
  },
  {
    id: 34,
    name: 'سبإ',
    transliteration: 'Saba',
    translation: 'سبا',
    type: 'Mecca',
    total_verses: 54,
  },
  {
    id: 35,
    name: 'فاطر',
    transliteration: 'Fatir',
    translation: 'پیدا کرنے والا',
    type: 'Mecca',
    total_verses: 45,
  },
  {
    id: 36,
    name: 'يس',
    transliteration: 'Ya-Sin',
    translation: 'یٰسٓ',
    type: 'Mecca',
    total_verses: 83,
  },
  {
    id: 37,
    name: 'الصافات',
    transliteration: 'As-Saffat',
    translation: 'صف باندھنے والے',
    type: 'Mecca',
    total_verses: 182,
  },
  {
    id: 38,
    name: 'ص',
    transliteration: 'Sad',
    translation: 'صٓ',
    type: 'Mecca',
    total_verses: 88,
  },
  {
    id: 39,
    name: 'الزمر',
    transliteration: 'Az-Zumar',
    translation: 'گروہ',
    type: 'Mecca',
    total_verses: 75,
  },
  {
    id: 40,
    name: 'غافر',
    transliteration: 'Ghafir',
    translation: 'بخشنے والا',
    type: 'Mecca',
    total_verses: 85,
  },
  {
    id: 41,
    name: 'فصلت',
    transliteration: 'Fussilat',
    translation: 'مفصل',
    type: 'Mecca',
    total_verses: 54,
  },
  {
    id: 42,
    name: 'الشورى',
    transliteration: 'Ash-Shuraa',
    translation: 'شورٰی',
    type: 'Mecca',
    total_verses: 53,
  },
  {
    id: 43,
    name: 'الزخرف',
    transliteration: 'Az-Zukhruf',
    translation: 'سونے کی چمک',
    type: 'Mecca',
    total_verses: 89,
  },
  {
    id: 44,
    name: 'الدخان',
    transliteration: 'Ad-Dukhan',
    translation: 'دھواں',
    type: 'Mecca',
    total_verses: 59,
  },
  {
    id: 45,
    name: 'الجاثية',
    transliteration: 'Al-Jathiyah',
    translation: 'زانوٗوں کے بل گری ہوئی',
    type: 'Mecca',
    total_verses: 37,
  },
  {
    id: 46,
    name: 'الأحقاف',
    transliteration: 'Al-Ahqaf',
    translation: 'ریگستان',
    type: 'Mecca',
    total_verses: 35,
  },
  {
    id: 47,
    name: 'محمد',
    transliteration: 'Muhammad',
    translation: 'محمدﷺ',
    type: 'Medina',
    total_verses: 38,
  },
  {
    id: 48,
    name: 'الفتح',
    transliteration: 'Al-Fath',
    translation: 'فتح',
    type: 'Medina',
    total_verses: 29,
  },
  {
    id: 49,
    name: 'الحجرات',
    transliteration: 'Al-Hujurat',
    translation: 'حجرے',
    type: 'Medina',
    total_verses: 18,
  },
  {
    id: 50,
    name: 'ق',
    transliteration: 'Qaf',
    translation: 'قٓ',
    type: 'Mecca',
    total_verses: 45,
  },
  {
    id: 51,
    name: 'الذاريات',
    transliteration: 'Adh-Dhariyat',
    translation: 'بکھیرنے والیاں',
    type: 'Mecca',
    total_verses: 60,
  },
  {
    id: 52,
    name: 'الطور',
    transliteration: 'At-Tur',
    translation: 'طور پہاڑ',
    type: 'Mecca',
    total_verses: 49,
  },
  {
    id: 53,
    name: 'النجم',
    transliteration: 'An-Najm',
    translation: 'ستارہ',
    type: 'Mecca',
    total_verses: 62,
  },
  {
    id: 54,
    name: 'القمر',
    transliteration: 'Al-Qamar',
    translation: 'چاند',
    type: 'Mecca',
    total_verses: 55,
  },
  {
    id: 55,
    name: 'الرحمن',
    transliteration: 'Ar-Rahman',
    translation: 'مہربان',
    type: 'Medina',
    total_verses: 78,
  },
  {
    id: 56,
    name: 'الواقعة',
    transliteration: "Al-Waqi'ah",
    translation: 'واقعہ ہونے والی قیامت',
    type: 'Mecca',
    total_verses: 96,
  },
  {
    id: 57,
    name: 'الحديد',
    transliteration: 'Al-Hadid',
    translation: 'فولاد',
    type: 'Medina',
    total_verses: 29,
  },
  {
    id: 58,
    name: 'المجادلة',
    transliteration: 'Al-Mujadila',
    translation: 'جھگڑنے والی',
    type: 'Medina',
    total_verses: 22,
  },
  {
    id: 59,
    name: 'الحشر',
    transliteration: 'Al-Hashr',
    translation: 'حشر',
    type: 'Medina',
    total_verses: 24,
  },
  {
    id: 60,
    name: 'الممتحنة',
    transliteration: 'Al-Mumtahanah',
    translation: 'امتحان لی جانے والی',
    type: 'Medina',
    total_verses: 13,
  },
  {
    id: 61,
    name: 'الصف',
    transliteration: 'As-Saf',
    translation: 'صف',
    type: 'Medina',
    total_verses: 14,
  },
  {
    id: 62,
    name: 'الجمعة',
    transliteration: "Al-Jumu'ah",
    translation: 'جمعہ',
    type: 'Medina',
    total_verses: 11,
  },
  {
    id: 63,
    name: 'المنافقون',
    transliteration: 'Al-Munafiqun',
    translation: 'منافقین',
    type: 'Medina',
    total_verses: 11,
  },
  {
    id: 64,
    name: 'التغابن',
    transliteration: 'At-Taghabun',
    translation: 'ہار جیت',
    type: 'Medina',
    total_verses: 18,
  },
  {
    id: 65,
    name: 'الطلاق',
    transliteration: 'At-Talaq',
    translation: 'طلاق',
    type: 'Medina',
    total_verses: 12,
  },
  {
    id: 66,
    name: 'التحريم',
    transliteration: 'At-Tahrim',
    translation: 'حرمت',
    type: 'Medina',
    total_verses: 12,
  },
  {
    id: 67,
    name: 'الملك',
    transliteration: 'Al-Mulk',
    translation: 'ملک',
    type: 'Mecca',
    total_verses: 30,
  },
  {
    id: 68,
    name: 'القلم',
    transliteration: 'Al-Qalam',
    translation: 'قلم',
    type: 'Mecca',
    total_verses: 52,
  },
  {
    id: 69,
    name: 'الحاقة',
    transliteration: 'Al-Haqqah',
    translation: 'حق ہونے والی',
    type: 'Mecca',
    total_verses: 52,
  },
  {
    id: 70,
    name: 'المعارج',
    transliteration: "Al-Ma'arij",
    translation: 'عروج',
    type: 'Mecca',
    total_verses: 44,
  },
  {
    id: 71,
    name: 'نوح',
    transliteration: 'Nuh',
    translation: 'نوح',
    type: 'Mecca',
    total_verses: 28,
  },
  {
    id: 72,
    name: 'الجن',
    transliteration: 'Al-Jinn',
    translation: 'جن',
    type: 'Mecca',
    total_verses: 28,
  },
  {
    id: 73,
    name: 'المزمل',
    transliteration: 'Al-Muzzammil',
    translation: 'کپڑا لپیٹنے والا',
    type: 'Mecca',
    total_verses: 20,
  },
  {
    id: 74,
    name: 'المدثر',
    transliteration: 'Al-Muddaththir',
    translation: 'کپڑا اوڑھنے والا',
    type: 'Mecca',
    total_verses: 56,
  },
  {
    id: 75,
    name: 'القيامة',
    transliteration: 'Al-Qiyamah',
    translation: 'قیامۃ',
    type: 'Mecca',
    total_verses: 40,
  },
  {
    id: 76,
    name: 'الانسان',
    transliteration: 'Al-Insan',
    translation: 'انسان',
    type: 'Medina',
    total_verses: 31,
  },
  {
    id: 77,
    name: 'المرسلات',
    transliteration: 'Al-Mursalat',
    translation: 'بھیجی جانے والی ہوائیں',
    type: 'Mecca',
    total_verses: 50,
  },
  {
    id: 78,
    name: 'النبإ',
    transliteration: 'An-Naba',
    translation: 'خبر',
    type: 'Mecca',
    total_verses: 40,
  },
  {
    id: 79,
    name: 'النازعات',
    transliteration: "An-Nazi'at",
    translation: 'زور سے کھینچنے والے',
    type: 'Mecca',
    total_verses: 46,
  },
  {
    id: 80,
    name: 'عبس',
    transliteration: "'Abasa",
    translation: 'تیوری چڑہائی',
    type: 'Mecca',
    total_verses: 42,
  },
  {
    id: 81,
    name: 'التكوير',
    transliteration: 'At-Takwir',
    translation: 'لپیٹنا',
    type: 'Mecca',
    total_verses: 29,
  },
  {
    id: 82,
    name: 'الإنفطار',
    transliteration: 'Al-Infitar',
    translation: 'ٹکڑے ہونا',
    type: 'Mecca',
    total_verses: 19,
  },
  {
    id: 83,
    name: 'المطففين',
    transliteration: 'Al-Mutaffifin',
    translation: 'ناپ تول میں کمی کرنے والے',
    type: 'Mecca',
    total_verses: 36,
  },
  {
    id: 84,
    name: 'الإنشقاق',
    transliteration: 'Al-Inshiqaq',
    translation: 'پھٹنا',
    type: 'Mecca',
    total_verses: 25,
  },
  {
    id: 85,
    name: 'البروج',
    transliteration: 'Al-Buruj',
    translation: 'برج',
    type: 'Mecca',
    total_verses: 22,
  },
  {
    id: 86,
    name: 'الطارق',
    transliteration: 'At-Tariq',
    translation: 'رات کو آنے والا',
    type: 'Mecca',
    total_verses: 17,
  },
  {
    id: 87,
    name: 'الأعلى',
    transliteration: "Al-A'la",
    translation: 'اعلی',
    type: 'Mecca',
    total_verses: 19,
  },
  {
    id: 88,
    name: 'الغاشية',
    transliteration: 'Al-Ghashiyah',
    translation: 'چھا جانے والی',
    type: 'Mecca',
    total_verses: 26,
  },
  {
    id: 89,
    name: 'الفجر',
    transliteration: 'Al-Fajr',
    translation: 'فجر',
    type: 'Mecca',
    total_verses: 30,
  },
  {
    id: 90,
    name: 'البلد',
    transliteration: 'Al-Balad',
    translation: 'شہر',
    type: 'Mecca',
    total_verses: 20,
  },
  {
    id: 91,
    name: 'الشمس',
    transliteration: 'Ash-Shams',
    translation: 'آفتاب',
    type: 'Mecca',
    total_verses: 15,
  },
  {
    id: 92,
    name: 'الليل',
    transliteration: 'Al-Layl',
    translation: 'رات',
    type: 'Mecca',
    total_verses: 21,
  },
  {
    id: 93,
    name: 'الضحى',
    transliteration: 'Ad-Duhaa',
    translation: 'دن کا چڑھنا',
    type: 'Mecca',
    total_verses: 11,
  },
  {
    id: 94,
    name: 'الشرح',
    transliteration: 'Ash-Sharh',
    translation: 'تسکین',
    type: 'Mecca',
    total_verses: 8,
  },
  {
    id: 95,
    name: 'التين',
    transliteration: 'At-Tin',
    translation: 'انجیر',
    type: 'Mecca',
    total_verses: 8,
  },
  {
    id: 96,
    name: 'العلق',
    transliteration: "Al-'Alaq",
    translation: 'جما ہوا خون',
    type: 'Mecca',
    total_verses: 19,
  },
  {
    id: 97,
    name: 'القدر',
    transliteration: 'Al-Qadr',
    translation: 'شب قدر',
    type: 'Mecca',
    total_verses: 5,
  },
  {
    id: 98,
    name: 'البينة',
    transliteration: 'Al-Bayyinah',
    translation: 'ثبوت',
    type: 'Medina',
    total_verses: 8,
  },
  {
    id: 99,
    name: 'الزلزلة',
    transliteration: 'Az-Zalzalah',
    translation: 'زلزلہ',
    type: 'Medina',
    total_verses: 8,
  },
  {
    id: 100,
    name: 'العاديات',
    transliteration: "Al-'Adiyat",
    translation: 'دوڑنے والے گھوڑے',
    type: 'Mecca',
    total_verses: 11,
  },
  {
    id: 101,
    name: 'القارعة',
    transliteration: "Al-Qari'ah",
    translation: 'کھڑکھڑاہٹ',
    type: 'Mecca',
    total_verses: 11,
  },
  {
    id: 102,
    name: 'التكاثر',
    transliteration: 'At-Takathur',
    translation: 'کثرت',
    type: 'Mecca',
    total_verses: 8,
  },
  {
    id: 103,
    name: 'العصر',
    transliteration: "Al-'Asr",
    translation: 'زمانہ',
    type: 'Mecca',
    total_verses: 3,
  },
  {
    id: 104,
    name: 'الهمزة',
    transliteration: 'Al-Humazah',
    translation: 'عیب لگانے والا',
    type: 'Mecca',
    total_verses: 9,
  },
  {
    id: 105,
    name: 'الفيل',
    transliteration: 'Al-Fil',
    translation: 'ہاتھی',
    type: 'Mecca',
    total_verses: 5,
  },
  {
    id: 106,
    name: 'قريش',
    transliteration: 'Quraysh',
    translation: 'قریش',
    type: 'Mecca',
    total_verses: 4,
  },
  {
    id: 107,
    name: 'الماعون',
    transliteration: "Al-Ma'un",
    translation: 'تھوڑی سی چیز',
    type: 'Mecca',
    total_verses: 7,
  },
  {
    id: 108,
    name: 'الكوثر',
    transliteration: 'Al-Kawthar',
    translation: 'جنت کی نہر',
    type: 'Mecca',
    total_verses: 3,
  },
  {
    id: 109,
    name: 'الكافرون',
    transliteration: 'Al-Kafirun',
    translation: 'کافرین',
    type: 'Mecca',
    total_verses: 6,
  },
  {
    id: 110,
    name: 'النصر',
    transliteration: 'An-Nasr',
    translation: 'نصرت',
    type: 'Medina',
    total_verses: 3,
  },
  {
    id: 111,
    name: 'المسد',
    transliteration: 'Al-Masad',
    translation: 'خوب بٹی ہوئی',
    type: 'Mecca',
    total_verses: 5,
  },
  {
    id: 112,
    name: 'الإخلاص',
    transliteration: 'Al-Ikhlas',
    translation: 'اخلاص',
    type: 'Mecca',
    total_verses: 4,
  },
  {
    id: 113,
    name: 'الفلق',
    transliteration: 'Al-Falaq',
    translation: 'صبح',
    type: 'Mecca',
    total_verses: 5,
  },
  {
    id: 114,
    name: 'الناس',
    transliteration: 'An-Nas',
    translation: 'انسان',
    type: 'Mecca',
    total_verses: 6,
  },
];
